VERSION 5.00
Begin VB.Form frmSeeXGF 
   Caption         =   "XGF Viewer"
   ClientHeight    =   8235
   ClientLeft      =   1665
   ClientTop       =   1545
   ClientWidth     =   6585
   LinkTopic       =   "Form2"
   ScaleHeight     =   8235
   ScaleWidth      =   6585
End
Attribute VB_Name = "frmSeeXGF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
